### ISSUE TITLE
Withdraw Ctoken In Single Pool

### ISSUE THREAD

**Issue by terryyyyyy** [nutbox-dao/nutbox-contract#3]
It only provide method to withdraw ctoken of all pools of a community.
But I think there is a need here for community that users can only withdraw ctoken of one pool

**Comment by tolak** [comment]
Done. See [here](https://github.com/nutbox-dao/nutbox-contract/commit/cbfbbd80125214a1d3cb77c72a3546f9a93870b5)

**Comment by terryyyyyy** [comment]
It's Ok now, close this issue
